### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ImNimboss** [neocord-lib/neocord#15]
Since this lib's design seems to be quite heavily based around dpy, why would I as a user want to use neocord? Couldn't I just use dpy or a fork instead?

**Comment by nerdguyahmad** [comment]
GitHub issues are for bug reports and feature requests, This type of questions are more suited to be asked in [Discord server](https://discord.gg/gHtYzjjYDX) so feel free to ask there later. :+1: 

Not anywhere in the project, I encouraged the usage of this library over discord.py or any of the forks. This is a work in progress project.
